project:
  type: website
  output-dir: docs
  
website:
  title: "Daniel Lopez"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - file: projects.qmd
        text: Projects
      - file: about.qmd
        text: About
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Daniel Lopez"

format:
  html:
    theme: lux
    toc: false

editor: source

