project:
  type: website
  output-dir: docs
  resources: 
    - images/
  
website:
  title: "Daniel Lopez"
  navbar:
    background: "#CDB490"
    left:
      - href: index.qmd
        text: Home
      - file: projects.qmd
        text: Projects
      - file: resume/index.qmd
        text: Resume
      - file: about.qmd
        text: About
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Daniel Lopez"

format:
  html:
    theme: [lux, custom.scss]
    toc: false

editor: source

