project:
  type: website
  output-dir: docs
  
website:
  title: "Daniel Lopez"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - file: projects.qmd
        text: Projects
      - file: about.qmd
        text: About
    tools:
      - icon: github
        href: https://github.com/Danielz529/
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Daniel Lopez"

format:
  html:
    theme: darkly
    toc: true

editor: source

